### ISSUE TITLE
runtime error on windows (exit code: 0xc000041d)

### ISSUE THREAD

**Issue by torresguilherme** [mistodon/gfx-hal-tutorials#10] opened 2020-06-09 02:20 UTC
hello,

i followed the first part of the tutorials and the triangle example works on Linux (using the vulkan backend) but on Windows (dx12), the window opens up as blank, does not respond, then it closes and I get the aforementioned exit code. there are no logs, or anything in the console that could potentially give me a clue on what is happening.

i know that my PC does support dx12. the GPU is a GeForce 635M with the default drivers you get from the nvidia utility for this GPU.

sorry if the info i'm giving is lacking, but that's about it :|

i appreciate any help.

**Comment by torresguilherme** [comment] 2020-06-09 13:01
i traced back with a debugger and found that the problem arises from this line: 
`                    let result = queue_group.queues[0].present_surface(
                        &mut res.surface,
                        surface_image,
                        Some(&res.rendering_complete_semaphore),
                    );
`
sending a None instead of the rendering_complete_semaphore doesn't solve change the outcome so I suppose it's a problem with the surface_image generation.

**Comment by mistodon** [comment] 2020-06-24 11:45
Hi there - I unfortunately don't have a machine capable of running DX12, so for the time being, I can't easily debug this :0

As soon as I'm able to though, I'll try get to the bottom of it.

**Comment by mistodon** [comment] 2020-09-29 13:03
I am now blessedly in possession of a windows PC and (with the updated versions of gfx/the tutorial) cannot reproduce this. Hopefully that means that it's fixed, so I'm going to optimistically close this issue. But if you are still seeing the error after pulling the latest version, please feel free to reopen this.

**Closed by mistodon** 2020-09-29 13:03 UTC

**Comment by torresguilherme** [comment] 2020-11-07 18:36
@mistodon thanks for your patience, but it took me an embarassingly long time to find out that my windows PC did not support vulkan (it creates a vulkan context, but actually do anything else)
