### ISSUE TITLE
[SOLVED]part00-triangle panics on building under Linux+Vulkan

### ISSUE THREAD

**Issue by Wolfman13** [Mistodon/gfx-hal-tutorials#5] opened 2018-11-28 07:55 UTC
I ran the code on Linux Ubuntu 18.10. I have rustc 1.30.1 and rustup 1.14.0(1e51b07cc 2018-10-04) installed. everything is just as it is in the tutorial but still I get this error message:

    Updating git repository `https://github.com/gfx-rs/gfx`
    Updating crates.io index                                                    
   Compiling cc v1.0.25                                                         
   Compiling semver-parser v0.7.0                                               
   Compiling proc-macro2 v0.4.24                                                
   Compiling bitflags v1.0.4                                                    
   Compiling libc v0.2.44                                                       
   Compiling unicode-xid v0.1.0                                                 
   Compiling gcc v0.3.55                                                        
   Compiling lazy_static v1.2.0                                                 
   Compiling core-foundation-sys v0.6.2                                         
   Compiling downcast-rs v1.0.3                                                 
   Compiling void v1.0.2                                                        
   Compiling rand_core v0.3.0                                                   
   Compiling pkg-config v0.3.14                                                 
   Compiling failure_derive v0.1.3                                              
   Compiling nix v0.11.0                                                        
   Compiling foreign-types-shared v0.1.1                                        
   Compiling stable_deref_trait v1.1.1                                          
   Compiling scopeguard v0.3.3                                                  
   Compiling cfg-if v0.1.6                                                      
   Compiling remove_dir_all v0.5.1                                              
   Compiling rustc-demangle v0.1.9                                              
   Compiling block v0.1.6                                                       
   Compiling byteorder v1.2.7                                                   
   Compiling percent-encoding v1.0.1                                            
   Compiling gfx-backend-metal v0.1.0 (https://github.com/gfx-rs/gfx?rev=d428a5d5#d428a5d5)
   Compiling xml-rs v0.7.0                                                      
   Compiling semver v0.9.0                                                      
   Compiling libloading v0.5.0                                                  
   Compiling backtrace-sys v0.1.24                                              
   Compiling spirv_cross v0.10.1                                                
   Compiling unreachable v1.0.0                                                 
   Compiling rand_isaac v0.1.1                                                  
   Compiling rand_hc v0.1.0                                                     
   Compiling rand_xorshift v0.1.0                                               
   Compiling rand_core v0.2.2                                                   
   Compiling objc_exception v0.1.1                                              
   Compiling foreign-types v0.3.2                                               
   Compiling owning_ref v0.4.0                                                  
   Compiling log v0.4.6                                                         
   Compiling x11-dl v2.18.3                                                     
   Compiling fxhash v0.2.1                                                      
error: failed to run custom build command for `gfx-backend-metal v0.1.0 (https://github.com/gfx-rs/gfx?rev=d428a5d5#d428a5d5)`
process didn't exit successfully: `/home/wolfman13/Game Dev/Rust/Tutorials/gfx-triangle/target/debug/build/gfx-backend-metal-88c05fb0bf7b314f/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=/home/wolfman13/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/d428a5d/src/backend/metal/shaders
cargo:rerun-if-changed=/home/wolfman13/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/d428a5d/src/backend/metal/shaders/fill.metal

--- stderr
thread 'main' panicked at 'failed to execute metal compiler: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed 

Can anyone please help :(

**Comment by Mistodon** [comment] 2018-12-03 12:36
Hey there! So it looks like the compiler thinks that you're compiling for macos. It's trying to use gfx-backend-metal instead of gfx-backend-vulkan.

I don't have a Vulkan environment to test on at the moment I'm afraid, but I suspect the problem is to do with either the `target_os` or `unix` cfg parameters for your platform.

If you can find the values of those parameters, or give any more details of your platform, OS, Rust install, it might help. Thanks :)

**Comment by Wolfman13** [comment] 2018-12-03 12:46
I had a similar issue when I used vulkano. The issue was that I had a space in the name of one of my parent directories. After changing the parent directory from "Game Dev" to "Game_Dev" the code runs without flaw...

**Comment by Mistodon** [comment] 2018-12-03 12:49
Wow, well I'm glad that's fixed it. Although that kind of seems like it might be a compiler bug, if a space in the path can trick it into thinking it's running on a different platform.

Regardless, I'll close this for now. If I can reproduce it one day I might add some more info here for others. :)

**Closed by Mistodon** 2018-12-03 12:49 UTC
